### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by g-r3m** [benlcollins/nestThermostatLogger#1]
Hi Ben, 

First thank you for your contribution to the Apps Script community 
Hopefully we will meet at some IRL Google meetups. 

I looked and tried your script. 
You are calling `makeRequest` but I can't find it in your repo. 

[
<img width="1440" alt="Screenshot 2021-02-14 at 11 52 49" src="https://user-images.githubusercontent.com/35274967/107874651-34e08080-6ebb-11eb-8e28-a61c7ad611a9.png">
](url)

Regards,
Jeremy

**Comment by benlcollins** [comment]
Hi Jeremy,

Great spot! Thanks so much for following up. I forgot to include that one in my write up. I've added that missing function to GitHub and in the article on my website. 

Cheers,
Ben
